# SPDX-FileCopyrightText: 2023 Loren Burkholder <computersemiexpert@outlook.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Linting

on:
  push

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.*'
          cache: true
          modules: 'qtmultimedia'
￼
      # Taken from https://github.com/sourcemeta/jsontoolkit/commit/2159d4aa26fba4bd77a0a5d9ce7c22233a79660f
￼      # See https://github.com/actions/runner-images/issues/8659
￼      - name: Work around actions/runner-images#8659
￼        run: |
￼          sudo rm -f /etc/apt/sources.list.d/ubuntu-toolchain-r-ubuntu-test-jammy.list
￼          sudo apt-get install --yes --allow-downgrades libc6=2.35-0ubuntu3.4 libc6-dev=2.35-0ubuntu3.4 libstdc++6=12.3.0-1ubuntu1~22.04 libgcc-s1=12.3.0-1ubuntu1~22.04

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build and check clang-tidy
        run: |
          mkdir build && cd build
          cmake -DRUN_CLANG_TIDY=ON ..
          cmake --build . -j $(nproc)
          cd ..

      - name: Check clang-format
        run: |
          ./format.sh

      - name: Codespell with annotations
        uses: codespell-project/actions-codespell@v2.0
        with:
          skip: ./build

      - name: Install reuse
        run: |
          sudo apt-add-repository universe
          sudo apt install reuse -y

      - name: Check for SPDX compliance
        run: |
          reuse lint
